export async function POST(request: Request) {
  try {
    const { messages, patientInfo } = await request.json()

    // Create a simple text-based report
    const reportContent = generateTextReport(messages, patientInfo)
    
    // Convert to PDF-like format (simplified for demo)
    const pdfBuffer = Buffer.from(reportContent, 'utf-8')

    return new Response(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename="medical-report.pdf"',
      },
    })

  } catch (error) {
    console.error('Report generation error:', error)
    return Response.json(
      { error: 'Failed to generate report' },
      { status: 500 }
    )
  }
}

function generateTextReport(messages: any[], patientInfo: any) {
  const currentDate = new Date().toLocaleDateString()
  const userMessages = messages.filter(m => m.type === 'user')
  const botMessages = messages.filter(m => m.type === 'bot')

  return `
🏥 DR. AI MEDICAL CONSULTATION REPORT
Generated on: ${currentDate}

👤 PATIENT INFORMATION
Name: ${patientInfo.name || 'Not provided'}
Age: ${patientInfo.age || 'Not provided'}
Gender: ${patientInfo.gender || 'Not provided'}
Weight: ${patientInfo.weight || 'Not provided'} kg
Height: ${patientInfo.height || 'Not provided'} cm
Blood Group: ${patientInfo.bloodGroup || 'Not provided'}
Emergency Contact: ${patientInfo.emergencyContact || 'Not provided'}

📊 CONSULTATION SUMMARY
Total Messages: ${messages.length}
Patient Concerns: ${userMessages.length}
AI Recommendations: ${botMessages.length}

🤔 PATIENT CONCERNS
${userMessages.map((msg, index) => `${index + 1}. ${msg.content}`).join('\n')}

💡 AI RECOMMENDATIONS
${botMessages.map((msg, index) => `${index + 1}. ${msg.content}`).join('\n')}

⚠️ MEDICAL DISCLAIMER
This report is generated by Dr. AI, an artificial intelligence medical assistant. 
The information provided is for educational and informational purposes only and 
should not be considered as medical advice, diagnosis, or treatment.

Always consult with qualified healthcare professionals for proper medical 
diagnosis, treatment, and care. This report is not a substitute for 
professional medical consultation.

If you are experiencing a medical emergency, please contact emergency 
services immediately.
`
}
